FROM node:6.1.0

# Set environment variables
ENV NODE_ENV development

# Install NPM dependencies
COPY package.json /var/<%= appname %>/
WORKDIR /var/<%= appname %>
RUN npm install

# Clone source files
ADD app.js /var/<%= appname %>/
ADD app /var/<%= appname %>/app
ADD config /var/<%= appname %>/config
ADD tests /var/<%= appname %>/tests

# Build static files
RUN npm run build

# Run
CMD npm start
